# Generated by Django 5.0.7 on 2024-07-25 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_rename_blog_news'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='nombre',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='autor',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='cuerpo',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='fecha_hora',
            new_name='date_time',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='imagen',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='resumen',
            new_name='summary',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='titulo',
            new_name='title',
        ),
        migrations.AddField(
            model_name='news',
            name='highlight',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
