# Generated by Django 5.0.7 on 2024-07-25 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_rename_nombre_category_name_rename_autor_news_author_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='highlight',
            new_name='highlight1',
        ),
        migrations.AddField(
            model_name='news',
            name='highlight2',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='highlight3',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='recent_post1',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='recent_post2',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='recent_post3',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
